server:
  port: 8080
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

openai:
  api-key: ${OPENAI_API_KEY:your-api-key-here}
  model: gpt-3.5-turbo
  temperature: 0.7
  max-tokens: 2000

logging:
  level:
    com.example: DEBUG
    org.springframework.web: INFO 